remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: [Power Outages]
description: [This is a data science project investigating the relationship between Power Outages and ...]
