remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
title: [Power Outages]
description: [This is a data science project investigating the characteristics behind major power outages]
gem "github-pages", group: :jekyll_plugins
